version: '3'
services:
  iexec-odb-p2p:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      PORT:   8000
      LISTEN: 1
      LOG:    trace
      DEBUG:  iexec-p2p-odb:*
      DATA:   /iexec-p2p-odb-data
    volumes:
      - ~/.iexec-p2p-odb-data:/iexec-p2p-odb-data


